version: '3.9'

services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 wsgi:application
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
